execute pathogen#infect()

"  ---------------------------------------------------------------------------
"  General
"  ---------------------------------------------------------------------------
set autoread
syntax on
set nobackup
set noswapfile
set noswapfile
set nofoldenable
set showmatch
set encoding=utf-8

"  ---------------------------------------------------------------------------
"  AUTOCOMPLETE
"  ---------------------------------------------------------------------------
set omnifunc=syntaxcomplete#Complete
set completeopt=menu,longest
inoremap <expr> <CR> pumvisible() ? "\<C-y>" : "\<C-g>u\<CR>"

"  ---------------------------------------------------------------------------
"  UI
"  ---------------------------------------------------------------------------

set number
set showtabline=2
set winwidth=81
set cursorline
set title
set autoindent
set smartindent
set showmode
set showcmd
set hidden
set go-=T
colorscheme ir_black
set mousehide

set mouse=a

" check to make sure vim has been compiled with colorcolumn support
" before enabling it
if exists("+colorcolumn")
  set colorcolumn=80
endif


"  ---------------------------------------------------------------------------
"  Text Formatting
"  ---------------------------------------------------------------------------
set tabstop=2
set shiftwidth=2
set softtabstop=2
set expandtab

set nowrap
set textwidth=100
set formatoptions=n

"  ---------------------------------------------------------------------------
"  Searching
"  ---------------------------------------------------------------------------

set incsearch
set hlsearch
set ignorecase

"  ---------------------------------------------------------------------------
"  Mappings
"  ---------------------------------------------------------------------------
" Turn off arrow keys (this might not be a good idea for beginners, but it is
" the best way to ween yourself of arrow keys on to hjkl)
" http://yehudakatz.com/2010/07/29/everyone-who-tried-to-convince-me-to-use-vim-was-wrong/

nnoremap <Left> :echoe "Use h"<CR>
nnoremap <Right> :echoe "Use l"<CR>
nnoremap <Up> :echoe "Use k"<CR>
nnoremap <Down> :echoe "Use j"<CR>

:nnoremap <C-a> :bnext<CR>

nmap <C-d> :Explore<CR>

"  ---------------------------------------------------------------------------
"  Plugins
"  ---------------------------------------------------------------------------

" eradicate all trailing whitespace all the time
let g:DeleteTrailingWhitespace = 1
let g:DeleteTrailingWhitespace_Action = 'delete'

" AutoClose
let g:AutoClosePairs = {'(': ')', '{': '}', '[': ']', '"': '"', "'": "'", '#{': '}'}
let g:AutoCloseProtectedRegions =  ["Comment", "String", "Character"]

" CtrlP
nmap <leader>f :CtrlP<cr>
nmap <leader>b :CtrlPBuffer<cr>
nmap <leader>l :CtrlPMRUFiles<cr>
let g:ctrlp_working_path_mode = 'ra'
let g:ctrlp_show_hidden = 1
let g:ctrlp_max_files = 9999999
let g:ctrlp_lazy_update = 1
" let g:ctrlp_custom_ignore = '\v[\/]\.(git|hg|svn)$'
let g:ctrlp_custom_ignore = 'node_modules\|DS_Store\|git\|public/assets\|public/cached-assets\|public/cms-assets\|public/assets/source_maps\|doc'
" let g:ctrlp_custom_ignore = '\.git$\|\.hg$\|\.svn$\|\.yardoc\|public\/images\|public\/assets\|public\/cms-assets\|public\/cached-assets\|public\/system\|data\|log\|tmp$'

" Ignore some binary, versioning and backup files when auto-completing
set wildignore=.svn,CVS,.git,*.swp,*.jpg,*.png,*.gif,*.pdf,*.bak,*source_maps*,*node_modules*,public/cached-assets*,doc
let g:fuzzy_ignore = "*.png;*.PNG;*.JPG;*.jpg;*.GIF;*.gif;vendor/**;coverage/**;tmp/**;rdoc/**;node_modules/**;public/cached-assets/**;doc/**"
" Set a lower priority for .old files
set suffixes+=.old
